name: Deploy Ubuntu Latest

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

# liste des jobs à exécuter
jobs:
    deploy:
        # démarre une image ubuntun
        runs-on: ubuntu-latest
            

     # Services nécessaires : Base de données MySQL 8
        services:
          mysql:
              image: mysql:8
              env:
                  MYSQL_ROOT_PASSWORD: root
                  MYSQL_DATABASE: cypress
              ports:
                  - 3306:3306
              options: >-
                --health-cmd="mysqladmin ping -h localhost" 
                --health-interval=10s 
                --health-timeout=5s 
                --health-retries=5

        steps:
          # Récupérer le code du projet (action github)
          - name: Récupérer le code du projet
            uses: actions/checkout@v4

          #Installer PHP (même version que l'environnement dev)
          - name: Installer PHP et Composer
            uses: shivammathur/setup-php@v2
            with:
                php-version: 8.2
                extensions: mbstring, intl, pdo_mysql, sodium
                tools: composer:v2

          # Configurer le projet (dev -> test)
          - name: Configurer l'environnement
            run: |
              cp .env .env.test
              echo "APP_ENV=test" >> .env
              echo "APP_ENV=test" >> .env.test
              echo "DATABASE_URL=mysql://root:root@127.0.0.1:3306/cypress" >> .env

          # Installer composer
          - name: Installer composer
            run: composer install --no-interaction --prefer-dist

          # Migrer la base de données
          - name: Migrer la base de données
            run: |
              php bin/console d:m:m

          # Démarrer le serveur PHP
          - name: Démarrer le serveur PHP
            run: php -S 127.0.0.1:8000 -t public &

          # Lancer les tests Cypress
          - name: Lancer les tests Cypress
            uses: cypress-io/github-action@v6